Update recipes/web.rb
Fix for:
FATAL: Chef::Mixin::Template::TemplateError: undefined method `each' for "zabbix":String

Change to array and set default in attributes file.